### ISSUE TITLE
dose not work for 1.16

### ISSUE THREAD

**Issue by CJH4000** [alt03b1/BedrockVanillaTweaks#2]
does not work for 1.16 you do not see the new texter or the zombie pigman

**Comment by RedCarlos26** [comment]
It’s happening for me two. Whenever I have a pack enabled, the texture isn’t good for the zombie Pigman

**Comment by alt03b1** [comment]
texture updates will start to be pushed tomorrow!

**Comment by RedCarlos26** [comment]
Ok thanks for the info! Happy to see that coming for 1.16!!

**Comment by RedCarlos26** [comment]
Also I have a a little question: the link for the lower shield pack isn’t working. It sends me on curse but nothing happens.

**Comment by alt03b1** [comment]
updated the link just now, it sends to the page instead of the direct download

**Comment by RedCarlos26** [comment]
Ok thank you very much! Appreciate it!

**Comment by CJH4000** [comment]
Thank you.
