### ISSUE TITLE
None work in 1.16.0

### ISSUE THREAD

**Issue by JessieTime2343** [alt03b1/BedrockVanillaTweaks#4]
I have been trying to use the smooth glass and it won’t let me use it. It says failed to upload and I don’t understand why. If anyone can help, that’d be nice.

-JessieTime2343

P.S. I’ve tried the others and it’s the same result!

**Comment by lithium-lx** [comment]
Hey, I'm a contributor to this repository. My partner is already working on updated texturepacks for 1.16. Since we are only two people, so this could take a bit. Sorry for the inconvenience.
