### ISSUE TITLE
How to I put this on my mcpe

### ISSUE THREAD

**Issue by dave318** [alt03b1/BedrockVanillaTweaks#5]

**Comment by RedCarlos26** [comment]
Are you on Android or IOS?

**Comment by RedCarlos26** [comment]
Hello?

**Comment by KaanGaming** [comment]
If you have a .mcpack file and have no clue on how to open it, try to open it with Minecraft (if you know what I mean.) There are apps that can do it if you cannot do it normally on your OS. Guaranteed to work with Android and I tested this myself a couple of times. It may take a few tries, but it works nonetheless. Sometimes the pack may appear corrupt or cannot be opened, contact the author with the issue you encountered.

**Comment by KaanGaming** [comment]
I opened a PR about it, this adds a tutorial for everyone to use. As for now, it is 100% ready to be merged, both for Windows and Android users. If you are not satisfied about it please tell me the reasons and parts you are not satisfied about.

**Comment by lithium-lx** [comment]
This issue will be closed. Please look at #7 for more info.
